<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Snt.Romashka.Db.Core.Abstracts\Snt.Romashka.Db.Core.Abstracts.csproj" />
      <ProjectReference Include="..\Snt.Romashka.Repositories.Abstracts\Snt.Romashka.Repositories.Abstracts.csproj" />
    </ItemGroup>

</Project>
